version: '3.9'
name: tp0
services:
  server:
    container_name: server
    image: server:latest
    entrypoint: python3 /main.py
    environment:
      - PYTHONUNBUFFERED=1
      - LOGGING_LEVEL=DEBUG
    volumes:
      - ./server/config.ini:/config.ini
    networks:
      - testing_net
  netcat:
    container_name: netcat
    build:
      context: .
      dockerfile: netcat/Dockerfile
    entrypoint: sh netcat_echo.sh
    depends_on:
      - server
    networks:
      - testing_net

  client1:
    container_name: client1
    image: client:latest
    entrypoint: /client
    environment:
      - CLI_ID=1
      - CLI_LOG_LEVEL=DEBUG
      - CLI_FIRSTNAME=name1
      - CLI_LASTNAME=l_name1
      - CLI_DOCUMENT=12341
      - CLI_BIRTHDATE=1999-03-11
      - CLI_NUMBER=98761
    volumes:
      - ./client/config.yaml:/config.yaml
    networks:
      - testing_net
    depends_on:
      - server

networks:
  testing_net:
    ipam:
      driver: default
      config:
        - subnet: 172.25.125.0/24
